Revert "Define two variables for the equations size, to simplify tuning the final pdf"
This reverts commit 2b4b9970c5ba564cdf29ee8689733ca0e6bc9601. Compiling
the pdf fails with

org.apache.fop.apps.FOPException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
javax.xml.transform.TransformerException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.