RFC: generating the PTZ specs with Github actions (#700)
* First example

* Test to try to fix rendering on developer.onvif.org

* Automatically generated SVG images

* Yet another fix to display equations

* Fixing inline equations size

* Experiment with formulas

* Automatically generated SVG images

* Formulas enhancements

* Still testing alpha

* Automatically generated SVG images

* Section 5.7.1.5

* Automatically generated SVG images

* Section 5.7.1.5.1

* Automatically generated SVG images

* Adding multiple new equations

* Fixing mml

* Automatically generated SVG images

* Completing Annex B GeoMove

* Automatically generated SVG images

* Fixing equation

* Automatically generated SVG images

* Yet another test

* Move from &ApplyFunction; to &#x2061;

* Making the workflow better

* Update

* Test

* Explaining why it seems that we do are not updating the images

* Recreating image

* Automatically generated SVG images

* Renamed PTZ -> Ptz to match the Media folder

* Wrap media objects in para

* Yet another test to render online

* Applying the fix to the rest od the document

* Test for rendering with the right size

* Define two variables for the equations size, to simplify tuning the final pdf

* Update the github action, to support manual execution.

* Revert "Define two variables for the equations size, to simplify tuning the final pdf"

This reverts commit 2b4b9970c5ba564cdf29ee8689733ca0e6bc9601. Compiling
the pdf fails with

org.apache.fop.apps.FOPException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
javax.xml.transform.TransformerException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

* Reducing the inlined formula size to 4mm for better reading

* Revert "Update the github actin, to support manual execution."

Reverting because I al pushing it to development before this PR is
accepted

* Fine tuning the size of the equations

* Additional tuning

* Reapply "Update the github actin, to support manual execution."

This reverts commit 8e9f58fb91605c13cb0eaa10538526d3dbfe05b3.

* Align the same equation and the same size in 5.7.1.5 and A.3.6

* Enhancing the github actions, to show better info

* bugfix

---------

Co-authored-by: ocampana-videotec <ocampana-videotec@users.noreply.github.com>